/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=prod --include-runtime=false` (hash: 709f058e214f64abf31ab881542c5320)
interface __BaseEnv_Env {
	KV: KVNamespace;
	CONTROL_LOGS: KVNamespace;
	TRADING_KV: KVNamespace;
	MCP_WORKERS_PROMPT: KVNamespace;
	GS_ASSETS: R2Bucket;
	MAIL_ARCHIVE: R2Bucket;
	TELEMETRY: R2Bucket;
	RISK_RADAR_R2: R2Bucket;
	PLATFORM_DB: D1Database;
	AUDIT_DB: D1Database;
	SIGNALS_DB: D1Database;
	RISK_RADAR_DB: D1Database;
	JOBS_DB: D1Database;
	PAPER_DB: D1Database;
	EMAIL: SendEmail;
	JOBS_QUEUE: Queue;
	EVENTS_QUEUE: Queue;
	MAIL_JOBS_QUEUE: Queue;
	BREVO_API_KEY: SecretsStoreSecret;
	BREVO_MCP_KEY: SecretsStoreSecret;
	AI: Ai;
	ENV: "production";
	AI_SEARCH_PUBLIC_ENDPOINT: "https://f800ea69-7ef4-4094-ba29-de38736fd22f.search.ai.cloudflare.com";
	CLOUDFLARE_ACCESS_AUDIENCE: "8510d42c31fc791e295427031ffeef7c7ebc0f1b62d8634fbb284bf82562f528";
	CLOUDFLARE_ACCESS_APPLICATION: "api-production";
	ADMIN_PROXY_AUDIENCE: "c520a7647223b49b20fbe5be240772863eb684b97b57c08955b6104c58170db9";
	CLOUDFLARE_SERVICE_ACCESS_AUDIENCE: "7ad07891d7c74cf243bb276b5941a75a3fcdc7301addb662a8b21df3e679c4a1";
	CLOUDFLARE_TEAM_DOMAIN: "goldshore.cloudflareaccess.com";
	GOOGLE_OAUTH_CLIENT_ID: "1054833139648-gt5o3k9uqhltt08nne0sigh8l3vodji7.apps.googleusercontent.com";
	GOOGLE_OAUTH_REDIRECT_URI: "https://api.goldshore.ai/goldclaw/oauth/google/callback";
	GOOGLE_BUSINESS_OAUTH_REDIRECT_URI: "https://api.goldshore.ai/admin/google/oauth/callback";
	GOOGLE_BUSINESS_OWNERSHIP_VERIFIED: "false";
	GOOGLE_OAUTH_PRODUCTION_APPROVED: "false";
	GOOGLE_WORKSPACE_SYNC_ENABLED: "false";
	GOOGLE_WORKSPACE_DELEGATED_ADMIN: "";
	GOOGLE_WORKSPACE_CUSTOMER_ID: "my_customer";
	GOOGLE_WORKSPACE_GROUP_ROLE_MAP: "{}";
	GOOGLE_WORKSPACE_ACCESS_APPLICATIONS: "admin-production,api-production";
	GITHUB_OAUTH_REDIRECT_URI: "https://api.goldshore.ai/auth/github/callback";
	CONTACT_NOTIFICATION_EMAILS: "marstonr6@gmail.com";
	MAIL_FORWARD_TO: "marstonr6@gmail.com";
	PUBLIC_SITE_URL: "https://goldshore.ai";
	MAIL_FROM_EMAIL: "noreply@goldshore.ai";
	MAIL_FROM_NAME: "GoldShore";
	TURNSTILE_SITEKEY: "0x4AAAAAAESEtC0-1kwdI9_7";
	AUTH_SESSION: DurableObjectNamespace<import("./src/index").AuthSession>;
	GS_SIGNALS: Workflow<Parameters<import("./src/index").SignalsEvaluator['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "AuthSession";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENV" | "AI_SEARCH_PUBLIC_ENDPOINT" | "CLOUDFLARE_ACCESS_AUDIENCE" | "CLOUDFLARE_ACCESS_APPLICATION" | "ADMIN_PROXY_AUDIENCE" | "CLOUDFLARE_SERVICE_ACCESS_AUDIENCE" | "CLOUDFLARE_TEAM_DOMAIN" | "GOOGLE_OAUTH_CLIENT_ID" | "GOOGLE_OAUTH_REDIRECT_URI" | "GOOGLE_BUSINESS_OAUTH_REDIRECT_URI" | "GOOGLE_BUSINESS_OWNERSHIP_VERIFIED" | "GOOGLE_OAUTH_PRODUCTION_APPROVED" | "GOOGLE_WORKSPACE_SYNC_ENABLED" | "GOOGLE_WORKSPACE_DELEGATED_ADMIN" | "GOOGLE_WORKSPACE_CUSTOMER_ID" | "GOOGLE_WORKSPACE_GROUP_ROLE_MAP" | "GOOGLE_WORKSPACE_ACCESS_APPLICATIONS" | "GITHUB_OAUTH_REDIRECT_URI" | "CONTACT_NOTIFICATION_EMAILS" | "MAIL_FORWARD_TO" | "PUBLIC_SITE_URL" | "MAIL_FROM_EMAIL" | "MAIL_FROM_NAME" | "TURNSTILE_SITEKEY">> {}
}
