name = "gs-www-redirect"
main = "src/index.ts"
compatibility_date = "2026-04-04"
workers_dev = false

[env.production]
name = "gs-www-redirect-prod"
routes = [
  { pattern = "www.goldshore.ai", custom_domain = true, override_existing_origin = true },
  { pattern = "www.goldshore.org", custom_domain = true, override_existing_origin = true }
]
