name = "gs-web"
compatibility_date = "2026-04-18"
pages_build_output_dir = "./dist"

[env.prod]
routes = [
  { pattern = "goldshore.ai", custom_domain = true },
  { pattern = "goldshore.org", custom_domain = true },
  { pattern = "rmarston.com", custom_domain = true }
]

[env.production]
routes = [
  { pattern = "goldshore.ai", custom_domain = true },
  { pattern = "goldshore.org", custom_domain = true },
  { pattern = "rmarston.com", custom_domain = true }
]
