name = "gs-agent"
main = "src/index.ts"
compatibility_date = "2026-04-18"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

[env.prod]
routes = []

[env.prod.vars]
ENV = "production"
CLOUDFLARE_TEAM_DOMAIN = "goldshore.cloudflareaccess.com"

[[env.prod.queues.consumers]]
queue = "goldshore-jobs"
max_batch_size = 10
max_batch_timeout = 5

[[env.prod.kv_namespaces]]
binding = "AGENT_KV"
id = "25a1eeba1de14e06af18c45b1b2c9743"

[env.preview]
routes = []

[env.preview.vars]
ENV = "preview"
CLOUDFLARE_TEAM_DOMAIN = "goldshore.cloudflareaccess.com"

[[env.preview.kv_namespaces]]
binding = "AGENT_KV"
id = "25a1eeba1de14e06af18c45b1b2c9743"
