name = "armsway-com"
main = "src/index.ts"
compatibility_date = "2026-04-18"
workers_dev = false

[env.prod]
routes = [
  { pattern = "armsway.com/*", zone_name = "armsway.com" },
  { pattern = "www.armsway.com/*", zone_name = "armsway.com" }
]

[[env.prod.d1_databases]]
binding = "GS_AUDIT_DB"
database_name = "gs_audit_db"
database_id = "1ae71d76-188f-481b-91d9-db2d39013f68"

[[env.prod.r2_buckets]]
binding = "TELEMETRY_STORAGE"
bucket_name = "gs-telemetry-storage"
