import { Hono } from 'hono';
import { createConnection } from 'mysql2/promise';
import { getActor, logAdminAction, requirePermission } from '../../auth';
import { analyzeSql, sha256 } from '../../lib/sql-sync';
import type { Env, Variables } from '../../types';

const sqlSync = new Hono<{ Bindings: Env; Variables: Variables }>();
const idPattern = /^[a-z0-9][a-z0-9_-]{1,62}$/;
const audit = (c: any, action: string, metadata: Record<string, unknown>, status: 'success' | 'error' = 'success') => logAdminAction(c.env, { action, actor: getActor(c.get('accessClaims'), c.req.raw), status, metadata });
const publicProfile = (row: any, configured: boolean) => ({ ...row, bindingConfigured: configured, setup: configured ? null : { binding: 'HOSTGATOR_DB', product: 'Cloudflare Hyperdrive', driver: 'mysql2', network: 'Workers VPC or Tunnel/Access' } });

sqlSync.get('/sql-sync/readiness', requirePermission('system:read'), async (c) => {
  return c.json({ ready: Boolean(c.env.HOSTGATOR_DB), binding: 'HOSTGATOR_DB', driver: 'mysql2', nodeCompatibility: true, executionEnabled: Boolean(c.env.HOSTGATOR_DB), note: c.env.HOSTGATOR_DB ? 'Hyperdrive binding is available.' : 'Create and bind a real Hyperdrive configuration before execution. Planning remains available.' });
});

sqlSync.get('/sql-sync/profiles', requirePermission('system:read'), async (c) => { const rows = await c.env.PLATFORM_DB.prepare('SELECT id,name,provider,database_name,environment,binding_name,notes,status,created_at,updated_at FROM sql_sync_profiles ORDER BY updated_at DESC').all(); return c.json({ items: rows.results.map((row) => publicProfile(row, Boolean(c.env.HOSTGATOR_DB))) }); });

sqlSync.post('/sql-sync/profiles', requirePermission('system:write'), async (c) => {
  const body = await c.req.json<{ id?: string; name?: string; databaseName?: string; environment?: string; notes?: string }>().catch(() => null); const id = body?.id?.trim().toLowerCase() ?? ''; const databaseName = body?.databaseName?.trim() ?? '';
  if (!idPattern.test(id) || !body?.name?.trim() || body.name.length > 100 || !/^[A-Za-z0-9_$-]{1,64}$/.test(databaseName) || !['staging', 'production'].includes(body?.environment ?? '') || (body?.notes?.length ?? 0) > 1000) return c.json({ error: 'Valid profile ID, name, database, and environment are required.' }, 400);
  try { await c.env.PLATFORM_DB.prepare("INSERT INTO sql_sync_profiles(id,name,provider,database_name,environment,notes,status,created_by) VALUES(?,?,'hostgator-mysql',?,?,?, ?,?)").bind(id, body.name.trim(), databaseName, body.environment, body.notes?.trim() ?? '', c.env.HOSTGATOR_DB ? 'ready' : 'setup_required', getActor(c.get('accessClaims'), c.req.raw)).run(); } catch { return c.json({ error: 'SQL profile already exists.' }, 409); }
  await audit(c, 'sql.profile.create', { profileId: id, environment: body.environment, bindingConfigured: Boolean(c.env.HOSTGATOR_DB) }); return c.json({ id, status: c.env.HOSTGATOR_DB ? 'ready' : 'setup_required' }, 201);
});

sqlSync.get('/sql-sync/plans', requirePermission('system:read'), async (c) => { const profileId = c.req.query('profileId'); const where = profileId && idPattern.test(profileId) ? 'WHERE profile_id=?' : ''; const values = where ? [profileId] : []; const rows = await c.env.PLATFORM_DB.prepare(`SELECT id,profile_id,name,checksum,analysis_json,status,requested_by,approved_by,approved_at,executed_at,result_json,created_at,updated_at FROM sql_sync_plans ${where} ORDER BY created_at DESC LIMIT 100`).bind(...values).all<any>(); return c.json({ items: rows.results.map((row) => ({ ...row, analysis: JSON.parse(row.analysis_json), result: row.result_json ? JSON.parse(row.result_json) : null, analysis_json: undefined, result_json: undefined })) }); });

sqlSync.post('/sql-sync/plans', requirePermission('system:write'), async (c) => {
  const body = await c.req.json<{ profileId?: string; name?: string; sql?: string }>().catch(() => null); if (!body?.profileId || !idPattern.test(body.profileId) || !body.name?.trim() || body.name.length > 120 || typeof body.sql !== 'string') return c.json({ error: 'Profile, plan name, and SQL are required.' }, 400); const profile = await c.env.PLATFORM_DB.prepare('SELECT id FROM sql_sync_profiles WHERE id=? AND status!=\'disabled\'').bind(body.profileId).first(); if (!profile) return c.json({ error: 'Active SQL profile not found.' }, 404);
  let analysis; try { analysis = analyzeSql(body.sql); } catch (error) { return c.json({ error: error instanceof Error ? error.message : 'SQL analysis failed.' }, 400); } const checksum = await sha256(body.sql); const id = crypto.randomUUID(); await c.env.PLATFORM_DB.prepare('INSERT INTO sql_sync_plans(id,profile_id,name,sql_text,checksum,analysis_json,requested_by) VALUES(?,?,?,?,?,?,?)').bind(id, body.profileId, body.name.trim(), body.sql, checksum, JSON.stringify(analysis), getActor(c.get('accessClaims'), c.req.raw)).run(); await audit(c, 'sql.plan.create', { planId: id, profileId: body.profileId, checksum, counts: analysis.counts }); return c.json({ id, status: 'draft', checksum, analysis }, 201);
});

sqlSync.post('/sql-sync/plans/:id/approve', requirePermission('approvals:execute'), async (c) => {
  const body = await c.req.json<{ checksum?: string; confirmPhrase?: string }>().catch(() => null); const plan = await c.env.PLATFORM_DB.prepare("SELECT checksum,analysis_json,status FROM sql_sync_plans WHERE id=?").bind(c.req.param('id')).first<any>(); if (!plan) return c.json({ error: 'SQL plan not found.' }, 404); if (plan.status !== 'draft') return c.json({ error: 'Only draft plans can be approved.' }, 409); const analysis = JSON.parse(plan.analysis_json); if (body?.checksum !== plan.checksum) return c.json({ error: 'Plan checksum changed or was not confirmed.' }, 409); if (analysis.destructive && body?.confirmPhrase !== 'DELETE HOSTGATOR DATA') return c.json({ error: 'Destructive plans require the exact confirmation phrase.' }, 409);
  await c.env.PLATFORM_DB.prepare("UPDATE sql_sync_plans SET status='approved',approved_by=?,approved_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='draft'").bind(getActor(c.get('accessClaims'), c.req.raw), c.req.param('id')).run(); await audit(c, 'sql.plan.approve', { planId: c.req.param('id'), checksum: plan.checksum, destructive: analysis.destructive }); return c.json({ success: true, status: 'approved' });
});

sqlSync.post('/sql-sync/plans/:id/execute', requirePermission('approvals:execute'), async (c) => {
  if (!c.env.HOSTGATOR_DB) return c.json({ error: 'HOSTGATOR_DB Hyperdrive binding is not configured. No SQL was executed.' }, 503); const body = await c.req.json<{ checksum?: string; confirmPhrase?: string }>().catch(() => null); const plan = await c.env.PLATFORM_DB.prepare("SELECT p.id,p.sql_text,p.checksum,p.analysis_json,p.status,s.environment FROM sql_sync_plans p JOIN sql_sync_profiles s ON s.id=p.profile_id WHERE p.id=?").bind(c.req.param('id')).first<any>(); if (!plan) return c.json({ error: 'SQL plan not found.' }, 404); if (plan.status !== 'approved' || body?.checksum !== plan.checksum || body?.confirmPhrase !== 'EXECUTE APPROVED SQL') return c.json({ error: 'Approved plan, exact checksum, and execution confirmation phrase are required.' }, 409);
  const fresh = await sha256(plan.sql_text); if (fresh !== plan.checksum) return c.json({ error: 'Stored SQL checksum mismatch. Execution refused.' }, 409); const analysis = analyzeSql(plan.sql_text); await c.env.PLATFORM_DB.prepare("UPDATE sql_sync_plans SET status='executing',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='approved'").bind(plan.id).run();
  const connection = await createConnection({ host: c.env.HOSTGATOR_DB.host, user: c.env.HOSTGATOR_DB.user, password: c.env.HOSTGATOR_DB.password, database: c.env.HOSTGATOR_DB.database, port: c.env.HOSTGATOR_DB.port, disableEval: true, connectTimeout: 10_000 }); const results: Array<{ index: number; affectedRows?: number; rowCount?: number }> = [];
  try { await connection.beginTransaction(); for (const statement of analysis.statements) { const [result] = await connection.query(statement.sql); const packet = result as any; results.push({ index: statement.index, affectedRows: typeof packet?.affectedRows === 'number' ? packet.affectedRows : undefined, rowCount: Array.isArray(result) ? result.length : undefined }); } await connection.commit(); const summary = { statements: results, completedAt: new Date().toISOString() }; await c.env.PLATFORM_DB.prepare("UPDATE sql_sync_plans SET status='completed',executed_at=CURRENT_TIMESTAMP,result_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(JSON.stringify(summary), plan.id).run(); await audit(c, 'sql.plan.execute', { planId: plan.id, environment: plan.environment, checksum: plan.checksum, statementCount: results.length }); return c.json({ success: true, status: 'completed', result: summary }); }
  catch (error) { await connection.rollback().catch(() => undefined); const code = error && typeof error === 'object' && 'code' in error ? String((error as any).code) : 'SQL_EXECUTION_FAILED'; await c.env.PLATFORM_DB.prepare("UPDATE sql_sync_plans SET status='failed',result_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(JSON.stringify({ code }), plan.id).run(); await audit(c, 'sql.plan.execute', { planId: plan.id, code }, 'error'); return c.json({ error: 'SQL execution failed and was rolled back.', code }, 502); }
  finally { await connection.end().catch(() => undefined); }
});

export default sqlSync;
